server:
  port: 8762

spring:
  application:
    name: order-service
#  zipkin:
#    baseUrl: http://localhost:9411/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

restaurantsvc:
  host: ${RESTAURANT_SVC_HOST}
  port: ${RESTAURANT_SVC_PORT}
  orderverify:
    uri: order/verify?orderId=zzbb

kitchensvc:
  host: ${KITCHEN_SVC_HOST}
  port: ${KITCHEN_SVC_PORT}
  createticket:
    uri: ticket/create/112233
